### ISSUE TITLE
Problems to decrypt data

### ISSUE THREAD

**Issue by tubauwe** [calvinmetcalf/crypto-pouch#16] opened 2016-01-25 21:31 UTC
After testing PouchDB for my Ionic project, I tried to encrypt my data with crypto-pouch. But I got some problems with the decryption of my data. I think it isn't the fault of your plugin, but I would be very glad, if you could help me or even give me some advice:

First of all I changed the function for init my database from the following

```
function initDB() {
  _db = new PouchDB('myDatabase', {adapter: 'websql'});
  if (!_db.adapter) {
    _db = new PouchDB('myDatabase');
  }
}
```

to this modified code:

```
function initDB() {
  _db = new PouchDB('myDatabase', {adapter: 'websql'});
  if (!_db.adapter) {
    _db = new PouchDB('myDatabase');
  }
  return _db.crypto(password)
    .then(function(){
      return _db;
    });
}
```

And it seems if my data is being encrypted every time I post some new one. In the database every new document has got the fields 'nounce', 'data' and 'tag' and it isn't human readable. 

But I don't know how to change my code for reading from the database. Without encryption I wrote the following function:

```
function getAllData() {
  if (!_data) {
    return $q.when(_db.allDocs( {include_docs: true}))
      .then(function(docs) {
        _data = docs.rows.map(function(row) {
          return row.doc;
        });
        _db.changes({ live: true, since: 'now', include_docs: true})
          .on('change', onDatabaseChange);
        return _data;
      });
  } else {
    return $q.when(_data);
  }
}
```

I have tried different possibilities, but I have no idea, where my code has to be changed. Can you help me, please! Thank you very much in advance!

Here is the code of two additional functions that are used by getAllData():

```
function onDataBaseChange(change) {
  var index = findIndex(_data, change.id);
  var data = _data[index];

  if (change.deleted) {
    if (data) {
      _data.splice(index, 1);
    }
  }
  else {
    if (data && data._id === change.id) {
      _data[index] = change.doc;
    }
    else {
      _data.splice(index, 0, change.doc);
    }
  }
}
```

```
function findIndex(array, id) {
  var low = 0, high = array.length, mid;
  while (low < high) {
    mid = (low + high) >>> 1;
    array[mid]._id < id ? low = mid + 1 : high = mid;
  }
  return low;
}
```

**Comment by calvinmetcalf** [comment] 2016-01-26 13:51
is the issue that the allDocs call is returning encrypted documents ?

**Comment by tubauwe** [comment] 2016-01-26 17:00
After yesterday writing my post above, I tried some changes in my code with a bit of success. Because I intend to store different kinds of documents in my database, I removed _db.allDocs from getAllData and inserted a function for mapping instead. Here is my updated function:
```
function getAllData() {
  if (!_data) {
    return $q.when(_db.query(mapAllFaecher, { include_docs: true}))
      .then(function(docs) {
        _data = docs.rows.map(function(row) {
          return row.doc;
        });
        _db.changes({ live: true, since: 'now', include_docs: true})
          .on('change', onDatabaseChange);
        return _data;
      });
  } else {
    return $q.when(_data);
  }
}
```
And the function to map my documents is the following:
```
function mapAllTypOne(doc) {
      if (doc.type === 'typ_one') {
        console.log('map');
        emit(doc._id);
      }
    }
```
With these changes I got my documents decrypted. But if I insert a new one, the list isn't being updated automatically. After a reload in the browser or a new start of my app in android or iOS the new document is listed. 

Because of the behaviour I could say, that the problem is not the query, but I think it is the handling of database chances. Is this possible with crypto-pouch?

In the meantime I found another question: Is it possible to use design documents, when I use crypto-pouch? I think this could be useful to increase the performance if the amount of documents is crowing.

**Comment by calvinmetcalf** [comment] 2016-01-26 17:49
design documents should be able to be used

does your code have problems with .changes if the crypto plugin is not installed?

**Comment by tubauwe** [comment] 2016-01-27 16:57
No my code has no problems with .changes if the crypto plugin is not installed. I checked it again because the last version before using the plugin was with design documents.

Where have I to insert the design documents into the database - before or after the _db.crypt(...) call?

**Comment by tubauwe** [comment] 2016-01-31 13:17
After new analysis I found, that the error starts by inserting the new data. To do this I use:
```
function addData(data) {
  return $q.when(_db.post(data));
};
```
The console shows the following messages:

> Uncaught TypeError: must start with number, buffer, array or string
>    Buffer @ bundle.js:88
>    decrypt @ bundle.js:19957
>    outgoing @ bundle.js:17280
>    modifyChange @ bundle.js:17342
>    (anonymous function) @ bundle.js:17369
>    r.emit @ pouchdb-5.2.0.min.js:7
>    F.t.onChange @ pouchdb-5.2.0.min.js:8
>    (anonymous function) @ pouchdb-5.2.0.min.js:11
>    (anonymous function) @ bundle.js:17369
>    r.emit @ pouchdb-5.2.0.min.js:7
>    F.t.onChange @ pouchdb-5.2.0.min.js:8
>    o @ pouchdb-5.2.0.min.js:10
>    n @ pouchdb-5.2.0.min.js:10
>    v.get.onsuccess @ pouchdb-5.2.0.min.js:10
>
> Database has a global failure DOMException: Uncaught exception in event 
>     handler.h.onabort @ pouchdb-5.2.0.min.js:10

Perhaps this lines could help, to find the error.

**Comment by calvinmetcalf** [comment] 2016-01-31 13:38
what does data look like ?

**Comment by tubauwe** [comment] 2016-01-31 15:43
I have two different types of documents at the moment. Here are two example documents of each type:
```
{
  "_id": "907B2E5E-8BB1-C82C-8BD1-9DB8B647127C",
  "name": "example",
  "kuerzel": "ex",
  "type": "fach",
  "_rev": "1-82dec1ce0b721819394548763b404f9c"
}
```
```
{
  "_id": "A7486E9B-52E3-580A-8981-0B255B0E4A34",
  "name": "example",
  "notensystem": "Noten",
  "runden": "abschneiden",
  "type": "klasse",
  "_rev": "1-66b68665274b300d0972435ac44f5eef"
}
```
I think, my data isn't something special.

**Comment by calvinmetcalf** [comment] 2016-01-31 16:05
so since your using post, the data actually looks like 

```js
{
 "name": "example",
  "notensystem": "Noten",
  "runden": "abschneiden",
  "type": "klasse"
}
```

right? 

try clicking pause on uncaught exceptions and see where the error is in decrypt, I suspect it's an issue with filter pouch not passing the encrypted data or maybe omitting the _id field for some reason

**Comment by tubauwe** [comment] 2016-01-31 19:09
The first pause is for a exception in bundle.js an there in line 88, column 5 ("Uncaught TypeError: must start with number, buffer, array or string") and the next stop in pouchdb-5.2.0.min.js in line 8, column 5035. 

I hope this can help for analysis.

**Comment by calvinmetcalf** [comment] 2016-01-31 19:17
yeah the first error is from the buffer lib, I'm wondering which line in
the decrypt function, aka which line in here
https://github.com/calvinmetcalf/crypto-pouch/blob/master/index.js

**Comment by tubauwe** [comment] 2016-02-01 21:31
What possibilities do we have to find out? I'm quite new to ionic and javascript and unfortunately I don't know how to go on with this issue. I would be very glad, if you can help me.

**Comment by calvinmetcalf** [comment] 2016-02-02 13:13
check out the section on remote debuging here http://ionicframework.com/docs/v2/resources/developer-tips/, the chrome dev tools should let you not only pause on the error, but look at the call stack to see where the function that called the function that threw the error was

**Comment by tubauwe** [comment] 2016-02-02 17:24
I tried to find out by using the chrome dev tools. I inserted in _function decrypt (doc)_ in _bundle.js_ (line 19953) the keyword debugger to stop there. After this stop I used "Step over to next function call (F10)" to see more details. There seems everything all right until the second time the line 19958 (after inserting the debugger)
`var decipher = chacha.createDecipher(key, new Buffer(doc.nonce, 'hex'));`
I can see my inserted and decrypted data and after this step the error occurs. I'm not sure, if this can hel

**Comment by calvinmetcalf** [comment] 2016-02-02 17:45
ok I can confirm working on a fix

**Comment by calvinmetcalf** [comment] 2016-02-02 18:05
ok try version 1.2.0

**Comment by tubauwe** [comment] 2016-02-03 21:20
Sorry, but there's no change. The problem is still the same. Could it be helpful for you, if I send you my code?

**Comment by calvinmetcalf** [comment] 2016-02-03 22:01
Wouldn't hurt, you see if you can isolate the smallest bit of code that
will reproduce it

**Comment by tubauwe** [comment] 2016-02-05 11:18
I've created an example ionic project, that shows the same error as descripted above. You can get the folder www of this project at 
[https://bitbucket.org/tubauwe/example.git](url). Thanks in advance.

**Comment by calvinmetcalf** [comment] 2016-02-05 12:26
and it turned out I didn't update the bundle in a while try now

**Comment by tubauwe** [comment] 2016-02-05 20:48
I tried immediataly after reading your last post: The behaviour changed. There's no error message, but after calling _saveData()_ there's nothing in the database. 

Compared to my example (on _bitbucket.org_) I only changed the content of www/lib/crypto-pouch to versino 1.2.1 of your plugi

**Comment by tubauwe** [comment] 2016-02-08 20:13
I tried again and now I'm sure, that the problem comes from handling changes. If I remove the listener for changes, there's no problem with writing documents to the database and even with using design documents. 

If this doesn't result in too low performance, I could live with. 

Another question: Do you have a suggestion, how to handle the password securely? It should be asked every start of the app and again after a given time of unactivity.

**Comment by calvinmetcalf** [comment] 2016-02-08 21:21
I'm going to look into the changes issues but if you can work without that
then good, for now, as for passwords, that's going to really depend on your
threat model.

**Comment by tubauwe** [comment] 2016-02-10 08:30
Thanks for your help so far.

I think my thread model isn't very special. All communication with the database is done by a javascript service, which gives the needed functions to use the database from the controller. 

But because I'm just at the beginning, I could change this, if it is helpful for security.

**Comment by garbados** [comment] 2021-08-06 23:12
@tubauwe Hey! It's been a while since you posted about this issue, but I want to check in and see if you still need help. I'm closing this issue for now but I can re-open it if you'd like :)

**Closed by garbados** 2021-08-06 23:12 UTC
