### ISSUE TITLE
Unencrypted replicated _deleted documents

### ISSUE THREAD

**Issue by xMartin** [calvinmetcalf/crypto-pouch#19] opened 2016-02-19 22:43 UTC
I replicated from a CouchDB and inspected the content of my indexeddb in Chrome. Found unencrypted data in documents with a `_deleted` flag. Non-deleted docs are encrypted as expected.

**Comment by calvinmetcalf** [comment] 2016-02-19 22:49
this is going to be an issue with [transform pouch](https://github.com/nolanlawson/transform-pouch ), but I expect that the issue is that it doesn't actually put documents that have been both created and deleted through the transform.

**Comment by garbados** [comment] 2021-08-06 23:08
Hey, it looks like this issue is [resolved](https://github.com/pouchdb-community/transform-pouch/pull/26#issuecomment-210194749) so I'm closing this for now. Let me know if you're still having problems!

**Closed by garbados** 2021-08-06 23:08 UTC
